name: 👤 User Service CI/CD - Fixed Structure
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Clean workspace
      run: |
        rm -rf obj bin
        rm -rf src/UserService/obj src/UserService/bin
        rm -rf src/UserService.Tests/obj src/UserService.Tests/bin
    
    - name: Restore dependencies
      run: dotnet restore src/UserService/UserService.csproj
    
    - name: Build main service
      run: dotnet build src/UserService/UserService.csproj --configuration Release --no-restore
    
    - name: Run tests
      run: dotnet test src/UserService.Tests/UserService.Tests.csproj --configuration Release --no-build --verbosity normal
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: user-service
        path: src/UserService/bin/Release/
