name: 👤 User Service CI/CD - Simple
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Clean and Restore
      run: |
        rm -rf src/UserService.Tests*
        dotnet clean
        dotnet restore user-service.csproj
    
    - name: Build
      run: dotnet build user-service.csproj --configuration Release
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: user-service
        path: bin/Release/
